### PR TITLE
Using the composer version of the smarty package

### PR DESCRIPTION
**Pull request by mamazu**
Smarty is now available and easily installable as a package which makes upgrading the it much easier. This pull request promotes your project to a package (because it has a composer.json in it). Now people who already have smarty in their project from the smarty package don't have to have it in their project twice (once for compiling and once for linting).

I also included a README.md in the merge request to line out how to use this packge. It would be even better if you publish the plugin on the packagist website then people could install it with just one simple command.

### CODE REVIEW

**Review by developerdino — APPROVED** [review]
Thanks @mamazu, I honestly forgot this package was even in my list of repos. Happy to accept this and I'll publish to Packagist for you to to make it easier to install.

**Comment by developerdino** [comment]
Hey @mamazu this is now available as a composer package in Packagist - https://packagist.org/packages/developerdino/smarty-lint

**Comment by mamazu** [comment]
Thanks, I will use your package then. Would you mind if I also updated the best practices in your plugin like "Composition over inheritance"?

**Comment by developerdino** [comment]
Feel free to send me any PRs you like. I'm happy for you to improve this in any way you can.

**Pull request merged**
